### ISSUE TITLE
vs2015 qt5.8

### ISSUE THREAD

**Issue by craigtao** [treefrogframework/chatapp#1]
use vs2015 + qt5.8 can compile this framework ？

**Comment by treefrogframework** [comment]
Maybe, yes.
I have not tried it..

**Comment by craigtao** [comment]
don't want solve? 🙂

**Comment by treefrogframework** [comment]
Try the latest TreeFrog.
https://github.com/treefrogframework/treefrog-framework/commit/a35367dbcdf6f5e85802ebe15629c3a945116885
